Traceback (most recent call last):
  File "D:\MAGIC\scripts\phase11\module_B\11B_credential_vault_manager_READY.py", line 2, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
